server:
  port: 8099

spring:
  profiles: zhongxiyi
  datasource:
    agent:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.opengauss.Driver
      url: jdbc:opengauss://172.16.16.147:5433/mydb?currentSchema=interface_agent
      username: myuser
      password: Helian!123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true

pagehelper:
  helper-dialect: postgresql