server:
  port: 8099

spring:
  profiles: kangshi
  datasource:
    agent:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://10.192.50.213:1433;DatabaseName=interface_agent;encrypt=false;trustServerCertificate=true
      username: sa
      password: Hljk@123.
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true

pagehelper:
  helper-dialect: sqlserver